[package]
name = "rusty-todos"
version = "0.1.0"
edition = "2024"
default-run = "rusty-todos"

[dependencies]
anyhow = "1"
jiff = "0.2.35"
serde = { version = "1", features = ["derive"] }
toasty = { version = "0.9", features = ["sqlite", "jiff"] }
toasty-cli = "0.9"
tokio = { version = "1", features = ["full"] }
topcoat = { version = "0.4.0", features = ["tailwind"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
topcoat = { version = "0.4.0", default-features = false, features = ["tailwind"] }
